# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
spring.application.name=servicio-usuarios
server.port=8081

# ==========================================
# CONEXIÓN A NEON TECH (POSTGRESQL)
# ==========================================
# Reemplaza los valores con la Connection String que te provee Neon.tech
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://ep-mute-silence-aqf2jlq3-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2CgulSTydBO3
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA / SPRINGDOC
# ==========================================
# "create-drop" creará las tablas al iniciar y las ELIMINARÁ por completo al apagar el microservicio
# CAMBIAR A 'update' PARA QUE LAS TABLAS NO SE ELIMINEN AL APAGAR EL SERVIDOR. 
# ('create-drop' borra todo, 'update' solo agrega columnas nuevas si hay cambios)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Muestra y formatea las consultas SQL en la consola del IDE (Ideal para revisar fallos)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilita la interfaz gráfica de Swagger UI en la ruta /swagger-ui/index.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true